### ISSUE TITLE
Dielectric Paste Recipe

### ISSUE THREAD

**Issue by PessimisticBastard** [owmii/Powah#6]
If I might make a suggestion, perhaps you could have a different way of crafting dielectric paste? I would suggest both keeping the current recipes and a two step recipe.

Perhaps craft together both the coal and the clay as is, but call it a "mix" and smelt it in the furnace to create the paste.

Or, alternatively, if you absolutely want lava to be part of the crafting recipe, keep the current recipe, but make a machine that combines liquid lava and the coal and clay.

**Comment by ChilledDayZ07** [comment]
I have to agree the recipe does need work I like the clay, coal mix idea.

**Comment by zeroneye** [comment]
I like the idea, i will try to add a Dielectric Paste smelting recipe. Thanks!

**Comment by ChilledDayZ07** [comment]
Hoping this is added soon as it’s gets old fast trying to craft a lot. It should be a mid game machine so players have to start out the hard way. Just my thoughts
